#pragma config(Sensor, port7,  TopButton,      sensorVexIQ_Touch)
#pragma config(Sensor, port8,  BottomButton,   sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          LeftDriveMotor, tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motor2,          MantisLeft,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor4,          RightArmMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor10,         LeftArmMotor,  tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         MantisRight,   tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         RightDriveMotor, tmotorVexIQ, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

short moveUpButton(){
	if(getBumperValue(TopButton)== 1){
		return BtnLUp;
	} else {
		return BtnRUp;
	}
}

short moveDownButton(){
	if(getBumperValue(BottomButton)== 1){
		return BtnLDown;
	} else {
		return BtnRDown;
	}
}

void hang(){
	repeatUntil (getBumperValue(BottomButton) == 1)
	{
		setMotor(RightArmMotor,-100);
		setMotor(LeftArmMotor,-100);
	}
	repeat(forever){
		stopAllMotors();
	}
}

task main()

{
	repeat(forever){
		armControl(RightArmMotor, moveUpButton(), moveDownButton(), 100);
		armControl(LeftArmMotor, moveUpButton(), moveDownButton(), 100);
		armControl(MantisLeft,BtnEUp,BtnEDown,50);
		armControl(MantisRight,BtnFUp,BtnFDown,50);
		tankControl(ChD,ChA, 0);
		if(getJoystickValue(BtnLDown)==1){
			hang();
		}
	}
}
