#pragma config(Sensor, port7,  TopButton,      sensorVexIQ_Touch)
#pragma config(Sensor, port8,  BottomButton,   sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          LeftDriveMotor, tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor2,          MantisLeft,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor4,          RightArmMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor10,         LeftArmMotor,  tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         MantisRight,   tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         RightDriveMotor, tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void raiseArmTop(){
	repeatUntil (getBumperValue(TopButton) == 1)
	{
		setMotor(RightArmMotor,100);
		setMotor(LeftArmMotor,100);
	}
}

void raiseArmBottom(){
	repeatUntil (getBumperValue(BottomButton) == 1)
	{
		setMotor(RightArmMotor,-100);
		setMotor(LeftArmMotor,-100);
	}
}

void runProgram(){
	turnRight(100,degrees,100);
	backward(0.7,seconds,75);
	moveMotor(MantisLeft,0.3,seconds,-100);
	moveMotor(MantisRight,0.3,seconds,-100);
	raiseArmTop();
	forward(1.7,seconds,100);
	raiseArmBottom();
}


task main()
{
waitUntil(getBumperValue(TopButton) == 1);
runProgram();
repeat(forever){
stopAllMotors();
};
}
