#pragma config(Sensor, port7,  TopButton,      sensorVexIQ_Touch)
#pragma config(Sensor, port8,  BottomButton,   sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          LeftDriveMotor, tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motor2,          MantisLeft,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor4,          RightArmMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor10,         LeftArmMotor,  tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         MantisRight,   tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         RightDriveMotor, tmotorVexIQ, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void moveArm(float timeToMove, int speed){
	setMotor(RightArmMotor, speed);
	setMotor(LeftArmMotor, speed);
	wait(timeToMove, seconds);
	stopAllMotors();
}

void raiseArmBottom(){
	repeatUntil (getBumperValue(BottomButton) == 1)
	{
		setMotor(RightArmMotor,-100);
		setMotor(LeftArmMotor,-100);
	}
}

void raiseArmTop(){
	repeatUntil (getBumperValue(TopButton) == 1)
	{
		setMotor(RightArmMotor,100);
		setMotor(LeftArmMotor,100);
	}

}
void getYellowHubGriffin(){
	repeatUntil(getBumperValue(TopButton) == 1)
	{
		setMotor(RightArmMotor,100);
		setMotor(LeftArmMotor,100);
	}
	turnLeft(70,degrees,100);
	moveArm(0.75,-100);
	forward(0.8,seconds,60);
	moveArm(0.8,100);
	backward(0.45,seconds,100);

}
void getYellowHubGriffinOP(){
	repeatUntil(getBumperValue(TopButton) == 1)
	{
		setMotor(RightArmMotor,100);
		setMotor(LeftArmMotor,100);
	}
	turnRight(63,degrees,100);  // was 70
	moveArm(0.75,-100);
	forward(0.8,seconds,60);
	moveArm(0.8,100);
	backward(0.35,seconds,100);

}





void runProgram(){
	//move mantis arms out of the way
	moveMotor(MantisLeft,100,degrees,50);
	moveMotor(MantisRight,100,degrees,50);
	//get yellow hub
	getYellowHubGriffinOP();
	//Cross Field
	//turnLeft(348,degrees,100);
	turnLeft(250,degrees,45);   // was 250
	forward(2.0,seconds,100);   // was 1.9
	//Push orange hubs into score zone
		// get first two orange hubs
		turnRight(110,degrees,50);
		forward(.8,seconds,100);
		turnRight(87,degrees,50);
		forward(0.4,seconds,45);
		moveMotor(MantisLeft,-100,degrees,50);
		//get third orange hub
		turnLeft(12,degrees,100);   // added this was 10
		forward(1.0,seconds,100);   // was 1.2
		turnLeft(10,degrees,100);   // was 20
		moveMotor(MantisRight,-100,degrees,50);
		backward(0.5,seconds,100);   // added this
		// push three hubs to corner
		turnLeft(95,degrees,50);    // was 90
		forward(0.9,seconds,100);   // was 0.2
		moveMotor(MantisLeft,100,degrees,50);
		moveMotor(MantisRight,100,degrees,50);
		forward(0.65,seconds,100);   // was 0.7
	//Stack Yellow Hub
	backward(0.4,seconds,100);
	moveArm(1.7,-80);
	moveArm(0.2,60);
	backward(0.8,seconds,100);
	//Get arms in down position
	moveMotor(MantisLeft,100,degrees,-50);
	moveMotor(MantisRight,100,degrees,-50);

}

void runSecondProgram(){
	//reset distanst from wall
	backward(0.3,seconds,100);
	wait(100,milliseconds);
	forward(0.16,seconds,100);
	//move mantis arms out of the way
	moveMotor(MantisLeft,80,degrees,50);
	moveMotor(MantisRight,80,degrees,50);
	//get yellow hub
	getYellowHubGriffin();
	//get orange hubs
	turnRight(60,degrees,100);
	moveArm(1,-100);
								/////////// Test Reset ///////////
								backward(0.55,seconds,100);
								forward(1.7,seconds,100);
								/////////// End Test Reset ///////////
	moveMotor(MantisLeft,90,degrees,-50);
	//turnLeft(10,degrees,100);
	//move to score zone
//	backward(1.68,seconds,100);

	setMotor(LeftDriveMotor,-100);
	setMotor(RightDriveMotor,-75);
	wait(1.68,seconds);

	turnLeft(219,degrees,100);
	forward(1.3,seconds,100);
	//backward(0.2,seconds,100);
	moveArm(0.3,80);
	//stack yellow
	moveMotor(MantisLeft,100,degrees,50);
	backward(0.8,seconds,100); // was 0.7
	turnRight(80,degrees,100);
	forward(0.4,seconds,100);
	turnLeft(165,degrees,100);
	forward(0.7,seconds,50);
	moveArm(0.9,-80);
	moveArm(0.4,60);
	backward(0.6,seconds,100);
}

void runThirdProgram(){
	turnRight(100,degrees,100);
	backward(0.7,seconds,75);
	moveMotor(MantisLeft,0.3,seconds,-100);
	moveMotor(MantisRight,0.3,seconds,-100);
	raiseArmTop();
	forward(1.3,seconds,100);
	raiseArmBottom();

	repeat(forever){
		stopAllMotors();
	}
}

task main()
{
	waitUntil(getBumperValue(TopButton) == 1);
	runProgram();
	waitUntil(getBumperValue(TopButton) == 1);
	runSecondProgram();
	waitUntil(getBumperValue(TopButton) == 1);
	runThirdProgram();

}
